ECSRA-57 Swagger documenttion
MariiaLobanova/E-Commerce-Shop-RESTful-API pull request #3
Opened 2024-01-12 15:04 UTC by MariiaLobanova

Added dependency in pom.xml, added needed endpoints in SecurityConfig class
![Image 12 01 24 at 15 56](https://github.com/MariiaLobanova/E-Commerce-Shop-RESTful-API/assets/144425535/b8b2d048-8aab-4f43-a72e-c7e293405410)
![Image 12 01 24 at 15 54](https://github.com/MariiaLobanova/E-Commerce-Shop-RESTful-API/assets/144425535/7acaf9fe-f691-458e-82da-3fe77781945d)
![Image 12 01 24 at 15 53](https://github.com/MariiaLobanova/E-Commerce-Shop-RESTful-API/assets/144425535/812c4671-288d-4f17-8a49-6bd78eefbbeb)

2024-01-14 20:29 UTC, MenilV requested changes
let's fix the other PR first as are some pieces of the same code in both PRs

2024-01-15 09:34 UTC, MariiaLobanova commented on pom.xml
> +			<scope>runtime</scope>
No, dont need, deleted its dependency

2024-01-15 10:58 UTC, MariiaLobanova commented on src/main/java/startsteps/ECommerceShop/config/JwtAuthenticationFilter.java
> +        jwt = authHeader.substring(7);
I gave a comment in previous PR: In my case "Bearer " includes 7 characters, and then goes token-genereted code and it is extracts this part to use. Is not  it ok?

2024-01-15 14:15 UTC, MenilV approved these changes
awesome, approved

2024-01-15 19:59 UTC, merged